import { StyleSheet } from 'react-native';
import { useDesignTokens } from '@pos/theme/native/design-tokens';

export type CartStyles = ReturnType<typeof createCartStyles>;

export const createCartStyles = (tokens: ReturnType<typeof useDesignTokens>) =>
    StyleSheet.create({
        root: {
            flex: 1,
            flexDirection: 'column',
        },
        emptyWrap: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            paddingHorizontal: tokens.spacing.lg,
        },
        emptyImage: {
            width: 220,
            height: 220,
            marginBottom: tokens.spacing.sm,
        },
        emptyText: {
            color: tokens.colors.textPrimary,
            fontSize: 20,
            fontWeight: '700',
            textAlign: 'center',
        },
        emptyHint: {
            color: tokens.colors.textSecondary,
            fontSize: 15,
            lineHeight: 22,
            textAlign: 'center',
            marginTop: tokens.spacing.xs,
            maxWidth: 260,
        },
        linesWrap: {
            flex: 1,
        },
        linesContent: {
            paddingBottom: tokens.spacing.sm,
        },
        actionsWrap: {
            marginTop: tokens.spacing.md,
        },
        checkoutSecondaryButtonContainer: {
            marginBottom: tokens.spacing.sm,
            borderRadius: tokens.radii.md,
            overflow: 'hidden',
        },
        checkoutSecondaryButton: {
            minHeight: 48,
            borderRadius: tokens.radii.md,
            borderWidth: 1,
            borderColor: tokens.colors.border,
            backgroundColor: tokens.colors.surface,
        },
        checkoutSecondaryButtonTitle: {
            color: tokens.colors.textPrimary,
            fontSize: 16,
            fontWeight: '700',
        },
        discountActionCard: {
            borderRadius: tokens.radii.md,
            borderWidth: 1,
            borderColor: tokens.colors.border,
            backgroundColor: tokens.colors.surfaceMuted,
            padding: tokens.spacing.sm,
            marginBottom: tokens.spacing.sm,
        },
        discountActionHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'flex-start',
            gap: tokens.spacing.sm,
        },
        discountHeaderMain: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'flex-start',
            gap: tokens.spacing.sm,
        },
        discountHeaderContent: {
            flex: 1,
        },
        discountHeaderMeta: {
            alignItems: 'flex-end',
            gap: tokens.spacing.xs,
        },
        discountCollapseButton: {
            width: 28,
            height: 28,
            borderRadius: 999,
            borderWidth: 1,
            borderColor: tokens.colors.border,
            backgroundColor: tokens.colors.surface,
            alignItems: 'center',
            justifyContent: 'center',
            marginTop: 2,
        },
        discountCollapseButtonText: {
            color: tokens.colors.textPrimary,
            fontSize: 14,
            fontWeight: '800',
        },
        discountActionTitle: {
            color: tokens.colors.textPrimary,
            fontSize: 16,
            fontWeight: '800',
        },
        discountActionHint: {
            color: tokens.colors.textSecondary,
            fontSize: 12,
            marginTop: 4,
        },
        discountActionStatus: {
            color: tokens.colors.accent,
            fontSize: 12,
            fontWeight: '700',
        },
        expandButton: {
            borderRadius: 999,
            borderWidth: 1,
            borderColor: `${tokens.colors.accent}55`,
            backgroundColor: `${tokens.colors.accent}12`,
            paddingHorizontal: tokens.spacing.sm,
            paddingVertical: 6,
        },
        expandButtonText: {
            color: tokens.colors.accent,
            fontSize: 12,
            fontWeight: '800',
        },
        discountCollapsedSummary: {
            color: tokens.colors.success,
            fontSize: 12,
            fontWeight: '800',
        },
        actionMutedCopy: {
            color: tokens.colors.textSecondary,
            fontSize: 12,
            marginTop: tokens.spacing.xs,
        },
        discountActionRow: {
            flexDirection: 'row',
            gap: tokens.spacing.xs,
            marginTop: tokens.spacing.sm,
        },
        discountActionButton: {
            flex: 1,
            borderRadius: 22,
            borderWidth: 1,
            paddingVertical: tokens.spacing.sm,
            paddingHorizontal: tokens.spacing.xs,
            alignItems: 'center',
            justifyContent: 'center',
            minHeight: 74,
        },
        discountActionButtonPromo: {
            borderColor: '#5CA9FF66',
            backgroundColor: '#5CA9FF18',
        },
        discountActionButtonManual: {
            borderColor: '#3FD38C66',
            backgroundColor: '#3FD38C18',
        },
        discountActionButtonOverride: {
            borderColor: '#F0A14A66',
            backgroundColor: '#F0A14A18',
        },
        discountActionButtonEyebrow: {
            color: tokens.colors.textSecondary,
            fontSize: 10,
            fontWeight: '800',
            letterSpacing: 1.2,
            marginBottom: 4,
        },
        discountActionButtonText: {
            color: tokens.colors.textPrimary,
            fontSize: 14,
            fontWeight: '800',
        },
        discountSecondaryButton: {
            flex: 1,
            borderRadius: 18,
            borderWidth: 1,
            borderColor: tokens.colors.border,
            backgroundColor: tokens.colors.surface,
            paddingVertical: tokens.spacing.sm,
            alignItems: 'center',
        },
        discountSecondaryButtonText: {
            color: tokens.colors.textSecondary,
            fontSize: 12,
            fontWeight: '700',
        },
        summaryValue: {
            color: tokens.colors.success,
            fontSize: 18,
            fontWeight: '800',
            marginTop: tokens.spacing.sm,
            marginBottom: tokens.spacing.xs,
        },
        summaryLine: {
            color: tokens.colors.textSecondary,
            fontSize: 13,
            lineHeight: 18,
        },
        promoChipRow: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            gap: tokens.spacing.xs,
            marginTop: tokens.spacing.xs,
        },
        promoChip: {
            borderRadius: 999,
            paddingHorizontal: tokens.spacing.xs,
            paddingVertical: 4,
            borderWidth: 1,
            borderColor: `${tokens.colors.accent}55`,
            backgroundColor: `${tokens.colors.accent}14`,
        },
        promoChipText: {
            color: tokens.colors.accent,
            fontSize: 12,
            fontWeight: '700',
        },
        promoChipStatic: {
            borderRadius: 999,
            paddingHorizontal: tokens.spacing.xs,
            paddingVertical: 4,
            borderWidth: 1,
            borderColor: `${tokens.colors.accent}55`,
            backgroundColor: `${tokens.colors.accent}14`,
        },
        warningText: {
            color: tokens.colors.danger,
            fontSize: 13,
            fontWeight: '700',
            textAlign: 'center',
            marginBottom: tokens.spacing.xs,
        },
        warningInline: {
            color: tokens.colors.warning,
            fontSize: 12,
            fontWeight: '700',
            marginTop: tokens.spacing.xs,
        },
        primaryButtonContainer: {
            borderRadius: tokens.radii.md,
            overflow: 'hidden',
        },
        primaryButton: {
            minHeight: 60,
            borderRadius: tokens.radii.md,
            backgroundColor: tokens.colors.accent,
        },
        primaryButtonDisabled: {
            minHeight: 60,
            borderRadius: tokens.radii.md,
            backgroundColor: tokens.colors.surfaceMuted,
            borderWidth: 1,
            borderColor: tokens.colors.border,
        },
        primaryButtonTitle: {
            fontSize: 20,
            fontWeight: '800',
        },
        primaryButtonTitleDisabled: {
            color: tokens.colors.textSecondary,
        },
        compactDialog: {
            width: 400,
        },
        paymentDialog: {
            width: 800,
            maxWidth: '94%',
            maxHeight: 680,
            minHeight: 580,
        },
        summaryDialog: {
            width: 560,
            maxHeight: 560,
            backgroundColor: 'transparent',
            padding: 0,
            borderWidth: 0,
            shadowColor: 'transparent',
        },
        summarySurface: {
            borderRadius: 28,
            borderWidth: 1,
            borderColor: '#C7D0DB33',
            backgroundColor: '#080B10',
            padding: tokens.spacing.xl,
            overflow: 'hidden',
        },
        summarySurfacePlain: {
            borderWidth: 0,
            borderColor: 'transparent',
            backgroundColor: 'transparent',
            paddingHorizontal: tokens.spacing.md,
            paddingVertical: tokens.spacing.sm,
            borderRadius: 0,
        },
        summaryDialogScroll: {
            maxHeight: 420,
        },
        summaryDialogContent: {
            paddingBottom: tokens.spacing.md,
        },
        mediumDialog: {
            width: 560,
        },
        dialogHeroCard: {
            borderRadius: 24,
            borderWidth: 1,
            borderColor: '#C7D0DB2E',
            backgroundColor: '#101722',
            padding: tokens.spacing.lg,
            marginBottom: tokens.spacing.md,
        },
        dialogSectionCard: {
            borderRadius: 22,
            borderWidth: 1,
            borderColor: '#C7D0DB24',
            backgroundColor: '#FFFFFF08',
            padding: tokens.spacing.md,
            marginBottom: tokens.spacing.sm,
        },
        dialogHeroMetaRow: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            gap: tokens.spacing.xs,
            marginTop: tokens.spacing.xs,
        },
        dialogHeroPill: {
            borderRadius: 999,
            borderWidth: 1,
            borderColor: '#C7D0DB33',
            backgroundColor: '#FFFFFF0D',
            paddingHorizontal: tokens.spacing.sm,
            paddingVertical: 6,
        },
        dialogHeroPillText: {
            color: tokens.colors.textPrimary,
            fontSize: 12,
            fontWeight: '700',
        },
        dialogTitle: {
            color: tokens.colors.textPrimary,
            fontSize: 24,
            fontWeight: '800',
            letterSpacing: -0.4,
            marginBottom: 6,
        },
        dialogHint: {
            color: tokens.colors.textSecondary,
            fontSize: 15,
            lineHeight: 22,
            marginBottom: tokens.spacing.md,
        },
        dialogInput: {
            borderWidth: 1,
            borderColor: tokens.colors.border,
            borderRadius: 18,
            backgroundColor: tokens.colors.surfaceMuted,
            color: tokens.colors.textPrimary,
            paddingHorizontal: tokens.spacing.sm,
            paddingVertical: tokens.spacing.sm,
            marginBottom: tokens.spacing.sm,
        },
        dialogInputLarge: {
            minHeight: 56,
            fontSize: 18,
            fontWeight: '700',
        },
        dialogActionRow: {
            flexDirection: 'row',
            justifyContent: 'flex-end',
            gap: tokens.spacing.sm,
            marginTop: tokens.spacing.md,
        },
        dialogSecondaryButton: {
            minHeight: 48,
            borderRadius: 18,
            paddingHorizontal: tokens.spacing.md,
        },
        dialogSecondaryButtonTitle: {
            color: tokens.colors.textSecondary,
            fontSize: 14,
            fontWeight: '800',
        },
        dialogPrimaryButton: {
            minHeight: 48,
            borderRadius: 18,
            paddingHorizontal: tokens.spacing.lg,
            backgroundColor: tokens.colors.accent,
        },
        dialogPrimaryButtonTitle: {
            color: '#ffffff',
            fontSize: 14,
            fontWeight: '800',
        },
        summarySection: {
            marginTop: tokens.spacing.md,
            paddingTop: tokens.spacing.md,
            borderTopWidth: 1,
            borderTopColor: `${tokens.colors.border}88`,
        },
        summarySectionTitle: {
            color: tokens.colors.textPrimary,
            fontSize: 15,
            fontWeight: '800',
            letterSpacing: 0.2,
            marginBottom: tokens.spacing.sm,
        },
        summaryItemRow: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'flex-start',
            gap: tokens.spacing.sm,
            borderRadius: tokens.radii.md,
            backgroundColor: `${tokens.colors.accent}0D`,
            paddingHorizontal: tokens.spacing.md,
            paddingVertical: tokens.spacing.md,
            marginBottom: tokens.spacing.sm,
        },
        summaryItemMain: {
            flex: 1,
        },
        summaryItemName: {
            color: tokens.colors.textPrimary,
            fontSize: 15,
            fontWeight: '800',
        },
        summaryItemMeta: {
            color: tokens.colors.textSecondary,
            fontSize: 13,
            marginTop: 6,
        },
        summaryDiscountLine: {
            color: tokens.colors.accent,
            fontSize: 13,
            fontWeight: '700',
            marginTop: 6,
        },
        summaryItemTotals: {
            alignItems: 'flex-end',
            minWidth: 110,
        },
        summaryItemOriginal: {
            color: tokens.colors.textSecondary,
            fontSize: 13,
            textDecorationLine: 'line-through',
        },
        summaryItemFinal: {
            color: tokens.colors.textPrimary,
            fontSize: 22,
            fontWeight: '800',
        },
        summaryItemSavings: {
            color: tokens.colors.success,
            fontSize: 13,
            fontWeight: '800',
            marginTop: 4,
        },
        totalRow: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginTop: tokens.spacing.sm,
        },
        totalRowStrong: {
            marginTop: tokens.spacing.sm,
            paddingTop: tokens.spacing.sm,
            borderTopWidth: 1,
            borderTopColor: tokens.colors.border,
        },
        totalLabel: {
            color: tokens.colors.textSecondary,
            fontSize: 14,
            fontWeight: '600',
        },
        totalLabelStrong: {
            color: tokens.colors.textPrimary,
            fontSize: 15,
            fontWeight: '800',
        },
        totalValue: {
            color: tokens.colors.textPrimary,
            fontSize: 15,
            fontWeight: '700',
        },
        totalValueSuccess: {
            color: tokens.colors.success,
            fontSize: 15,
            fontWeight: '800',
        },
        totalValueStrong: {
            color: tokens.colors.textPrimary,
            fontSize: 20,
            fontWeight: '800',
        },
        summarySecondaryButton: {
            minHeight: 48,
            borderRadius: 18,
            paddingHorizontal: tokens.spacing.md,
        },
        summarySecondaryButtonTitle: {
            color: tokens.colors.textSecondary,
            fontSize: 14,
            fontWeight: '800',
        },
        summaryFooter: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            gap: tokens.spacing.md,
            marginTop: tokens.spacing.lg,
            paddingTop: tokens.spacing.md,
            borderTopWidth: 1,
            borderTopColor: `${tokens.colors.border}88`,
        },
        summaryFooterTotalBlock: {
            flex: 1,
        },
        summaryFooterLabel: {
            color: tokens.colors.textSecondary,
            fontSize: 13,
            fontWeight: '700',
            textTransform: 'uppercase',
            letterSpacing: 1,
        },
        summaryFooterValue: {
            color: tokens.colors.textPrimary,
            fontSize: 32,
            fontWeight: '800',
            marginTop: 4,
        },
        summaryFooterActions: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: tokens.spacing.sm,
        },
        summaryPrimaryIconButton: {
            minWidth: 64,
            minHeight: 56,
            borderRadius: 20,
            backgroundColor: tokens.colors.accent,
            paddingHorizontal: tokens.spacing.md,
        },
        segmentRow: {
            flexDirection: 'row',
            gap: tokens.spacing.xs,
            marginBottom: tokens.spacing.sm,
        },
        segmentButton: {
            flex: 1,
            borderWidth: 1,
            borderColor: tokens.colors.border,
            borderRadius: 20,
            paddingVertical: tokens.spacing.sm,
            alignItems: 'center',
            backgroundColor: tokens.colors.surfaceMuted,
        },
        segmentButtonActive: {
            borderColor: `${tokens.colors.accent}88`,
            backgroundColor: `${tokens.colors.accent}18`,
        },
        segmentButtonText: {
            color: tokens.colors.textSecondary,
            fontWeight: '700',
        },
        segmentButtonTextActive: {
            color: tokens.colors.accent,
        },
        dialogSubheading: {
            color: tokens.colors.textPrimary,
            fontSize: 13,
            fontWeight: '800',
            marginTop: tokens.spacing.xs,
            marginBottom: tokens.spacing.xs,
        },
        dialogFieldHint: {
            color: tokens.colors.textSecondary,
            fontSize: 12,
            lineHeight: 18,
            marginBottom: tokens.spacing.xs,
        },
        manualValueCard: {
            borderRadius: 22,
            borderWidth: 1,
            borderColor: '#3FD38C33',
            backgroundColor: '#3FD38C0D',
            padding: tokens.spacing.md,
            marginBottom: tokens.spacing.sm,
        },
        savedDiscountCard: {
            borderRadius: 22,
            borderWidth: 1,
            borderColor: '#5CA9FF33',
            backgroundColor: '#5CA9FF0D',
            padding: tokens.spacing.md,
            marginBottom: tokens.spacing.sm,
        },
        savedDiscountList: {
            gap: tokens.spacing.xs,
            marginTop: tokens.spacing.xs,
        },
        savedDiscountButton: {
            borderRadius: 18,
            borderWidth: 1,
            borderColor: tokens.colors.border,
            backgroundColor: tokens.colors.surfaceMuted,
            paddingHorizontal: tokens.spacing.sm,
            paddingVertical: tokens.spacing.sm,
        },
        savedDiscountButtonActive: {
            borderColor: `${tokens.colors.accent}88`,
            backgroundColor: `${tokens.colors.accent}18`,
        },
        savedDiscountButtonTitle: {
            color: tokens.colors.textPrimary,
            fontSize: 14,
            fontWeight: '800',
        },
        savedDiscountButtonTitleActive: {
            color: tokens.colors.accent,
        },
        savedDiscountButtonMeta: {
            color: tokens.colors.textSecondary,
            fontSize: 12,
            marginTop: 4,
        },
        approvalCard: {
            borderRadius: 22,
            borderWidth: 1,
            borderColor: '#F0A14A33',
            backgroundColor: '#F0A14A0D',
            padding: tokens.spacing.md,
            marginTop: tokens.spacing.xs,
        },
    });
