import { Role } from '@pos/auth/data-access';
import { SidebarItem } from './definitions';

export const menuItems: SidebarItem[] = [
    {
        id: '1',
        title: 'Dashboard',
        labelKey: 'SIDEBAR_Dashboard',
        icon: 'view-dashboard-outline',
        role: Role.Admin,
        group: 'Core',
    },
    // {
    //     id: '2',
    //     title: 'Customers',
    //     icon: 'account-box-multiple-outline',
    //     role: Role.Admin,
    // },
    {
        id: '3',
        title: 'Reports',
        labelKey: 'SIDEBAR_Reports',
        icon: 'clipboard-list-outline',
        children: [
            { id: '3-0', title: 'End of Day', labelKey: 'SIDEBAR_EndOfDay' },
            { id: '3-1', title: 'Sale List', labelKey: 'SIDEBAR_SaleList' },
            { id: '3-2', title: 'By Employee', labelKey: 'SIDEBAR_ByEmployee' },
            { id: '3-3', title: 'By Product', labelKey: 'SIDEBAR_ByProduct' },
        ],
        role: Role.Admin,
        group: 'Core',
    },
    {
        id: '8',
        title: 'Employees',
        labelKey: 'SIDEBAR_Employees',
        icon: 'account-group-outline',
        role: Role.Admin,
        group: 'Management',
    },
    {
        id: '9',
        title: 'Discounts',
        icon: 'brightness-percent',
        role: Role.Admin,
        group: 'Management',
        children: [
            { id: '9-1', title: 'Discounts' },
            { id: '9-2', title: 'Promo Codes' },
            { id: '9-3', title: 'Policies' },
            { id: '9-4', title: 'Exceptions' },
        ],
    },
    {
        id: '5',
        title: 'Catalog',
        labelKey: 'SIDEBAR_Catalog',
        icon: 'qrcode',
        role: Role.Admin,
        group: 'Management',
        children: [
            { id: '5-1', title: 'Products', labelKey: 'SIDEBAR_Products' },
            { id: '5-2', title: 'Categories', labelKey: 'SIDEBAR_Categories' },
            { id: '5-3', title: 'U/M', labelKey: 'SIDEBAR_UM' },
            { id: '5-4', title: 'Brands', labelKey: 'SIDEBAR_Brands' },
        ],
    },
    {
        id: '4',
        title: 'Inventory',
        labelKey: 'SIDEBAR_Inventory',
        icon: 'warehouse',
        children: [
            { id: '4-1', title: 'In Stock', labelKey: 'SIDEBAR_InStock' },
            { id: '4-2', title: 'Counts', labelKey: 'SIDEBAR_Counts' },
            { id: '4-3', title: 'Receives', labelKey: 'SIDEBAR_Receives' },
        ],
        role: Role.Admin,
        group: 'Management',
    },
    // {
    //     id: '6',
    //     title: 'Users',
    //     icon: 'account-group-outline',
    //     role: Role.Admin,
    //     children: [
    //         { id: '6-1', title: 'Users' },
    //         { id: '6-2', title: 'Roles' },
    //     ],
    // },
    {
        id: '7',
        title: 'Settings',
        labelKey: 'SIDEBAR_Settings',
        icon: 'cog-outline',
        role: Role.Admin,
        group: 'Configuration',
        children: [
            { id: '7-0', title: 'General', labelKey: 'SIDEBAR_General' },
            { id: '7-1', title: 'Store', labelKey: 'SIDEBAR_Store' },
            { id: '7-2', title: 'Station', labelKey: 'SIDEBAR_Station' },
            { id: '7-3', title: 'Printers', labelKey: 'SIDEBAR_Printers' },
            { id: '7-4', title: 'Logs', labelKey: 'SIDEBAR_Logs' },
            // { id: '7-3', title: 'Receipt' },
        ],
    },
];
