import { StyleSheet } from 'react-native';
import { useTheme } from '@rneui/themed';
import { getThemeColors, useSharedStyles } from '@pos/theme/native';

export const useHomeScreenStyles = () => {
    const theme = useTheme();
    const colors = getThemeColors(theme);
    const sharedStyles = useSharedStyles();

    return StyleSheet.create({
        ...sharedStyles,
        container: {
            flex: 1,
            paddingHorizontal: 24,
            backgroundColor: '#05070b',
        },
        containerContent: {
            flexGrow: 1,
            justifyContent: 'center',
            paddingVertical: 32,
        },
        shell: {
            flexDirection: 'row',
            gap: 18,
            alignItems: 'stretch',
        },
        readyShell: {
            flexDirection: 'row',
            gap: 20,
            alignItems: 'stretch',
            minHeight: 560,
        },
        e2eShortcut: {
            position: 'absolute',
            top: 12,
            right: 12,
            width: 96,
            height: 24,
            zIndex: 10,
            opacity: 0.18,
            backgroundColor: 'rgba(255,255,255,0.08)',
            borderRadius: 6,
        },
        hero: {
            flex: 1,
            backgroundColor: '#10141b',
            borderRadius: 28,
            padding: 28,
            justifyContent: 'space-between',
            borderWidth: 1,
            borderColor: 'rgba(255, 255, 255, 0.08)',
            overflow: 'hidden',
        },
        pinHeroTop: {
            minHeight: 180,
            justifyContent: 'flex-end',
            position: 'relative',
        },
        pinBrandPlate: {
            width: 180,
            height: 180,
            borderRadius: 36,
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: 'rgba(255,255,255,0.02)',
            borderWidth: 1,
            borderColor: 'rgba(255,255,255,0.06)',
        },
        pinHeroGlow: {
            position: 'absolute',
            right: -24,
            top: -36,
            width: 220,
            height: 220,
            borderRadius: 110,
            backgroundColor: 'rgba(126,182,255,0.08)',
        },
        pinHeroBottom: {
            paddingTop: 24,
            maxWidth: 560,
        },
        businessLabel: {
            color: '#7eb6ff',
            textTransform: 'uppercase',
            letterSpacing: 2,
            marginBottom: 10,
            fontSize: 12,
            fontWeight: '700',
        },
        heroTitle: {
            color: '#f3f7ff',
            fontSize: 34,
            fontWeight: '700',
            lineHeight: 40,
            marginBottom: 10,
            maxWidth: 520,
        },
        heroSubtitle: {
            color: '#a3adba',
            fontSize: 15,
            lineHeight: 23,
            maxWidth: 500,
        },
        pinHeroMetaRow: {
            flexDirection: 'row',
            gap: 12,
            marginTop: 24,
        },
        pinHeroMetaChip: {
            flex: 1,
            minHeight: 88,
            borderRadius: 18,
            paddingHorizontal: 16,
            paddingVertical: 14,
            borderWidth: 1,
            borderColor: 'rgba(255,255,255,0.08)',
            backgroundColor: 'rgba(255,255,255,0.03)',
            justifyContent: 'space-between',
        },
        pinHeroMetaLabel: {
            color: '#7f8a9a',
            textTransform: 'uppercase',
            letterSpacing: 1.2,
            fontSize: 11,
            fontWeight: '700',
        },
        pinHeroMetaValue: {
            color: '#eef4ff',
            fontSize: 18,
            fontWeight: '700',
        },
        keypadCard: {
            width: 412,
            backgroundColor: '#10141b',
            borderRadius: 28,
            paddingHorizontal: 22,
            paddingVertical: 20,
            justifyContent: 'flex-start',
            borderWidth: 1,
            borderColor: 'rgba(255, 255, 255, 0.08)',
            shadowColor: '#000',
            shadowOpacity: 0.24,
            shadowRadius: 18,
            shadowOffset: { width: 0, height: 10 },
        },
        wizardCardWide: {
            width: 640,
        },
        setupWizardCard: {
            width: 460,
            paddingHorizontal: 26,
            paddingVertical: 24,
        },
        setupWizardHeader: {
            marginBottom: 18,
        },
        setupWizardEyebrow: {
            color: '#7eb6ff',
            textTransform: 'uppercase',
            letterSpacing: 1.8,
            fontSize: 11,
            fontWeight: '700',
            marginBottom: 8,
            textAlign: 'center',
        },
        setupWizardContent: {
            gap: 14,
        },
        setupHeroMetaRow: {
            flexDirection: 'row',
            gap: 12,
            marginTop: 28,
        },
        setupHeroMetaCard: {
            flex: 1,
            minHeight: 84,
            borderRadius: 18,
            paddingHorizontal: 16,
            paddingVertical: 14,
            borderWidth: 1,
            borderColor: 'rgba(255,255,255,0.08)',
            backgroundColor: 'rgba(255,255,255,0.03)',
            justifyContent: 'space-between',
        },
        setupHeroMetaLabel: {
            color: '#7f8a9a',
            textTransform: 'uppercase',
            letterSpacing: 1.2,
            fontSize: 11,
            fontWeight: '700',
        },
        setupHeroMetaValue: {
            color: '#eef4ff',
            fontSize: 18,
            fontWeight: '700',
        },
        wizardStepsPanel: {
            marginTop: 20,
            padding: 18,
            borderRadius: 22,
            borderWidth: 1,
            borderColor: 'rgba(255,255,255,0.08)',
            backgroundColor: 'rgba(255,255,255,0.03)',
            gap: 12,
        },
        wizardStepsEyebrow: {
            color: '#7f8a9a',
            textTransform: 'uppercase',
            letterSpacing: 1.6,
            fontSize: 11,
            fontWeight: '700',
        },
        keypadHeader: {
            alignItems: 'center',
            marginBottom: 8,
        },
        keypadEyebrow: {
            color: '#7eb6ff',
            textTransform: 'uppercase',
            letterSpacing: 1.8,
            fontSize: 11,
            fontWeight: '700',
            marginBottom: 8,
        },
        keypadTitle: {
            color: '#f4f8ff',
            fontSize: 23,
            fontWeight: '700',
            lineHeight: 30,
            marginBottom: 8,
            textAlign: 'center',
        },
        keypadHint: {
            color: '#a3adba',
            textAlign: 'center',
            marginBottom: 16,
            lineHeight: 20,
        },
        keypadWrap: {
            borderRadius: 24,
            paddingHorizontal: 10,
            paddingVertical: 12,
            backgroundColor: 'rgba(255,255,255,0.025)',
            borderWidth: 1,
            borderColor: 'rgba(255,255,255,0.06)',
        },
        pinUtilityPanel: {
            marginTop: 14,
            paddingTop: 14,
            borderTopWidth: 1,
            borderTopColor: 'rgba(255,255,255,0.08)',
        },
        pinUtilityTitle: {
            color: '#7f8a9a',
            textTransform: 'uppercase',
            letterSpacing: 1.2,
            fontSize: 11,
            fontWeight: '700',
            marginBottom: 10,
            textAlign: 'center',
        },
        pinLogoffButton: {
            paddingVertical: 12,
            alignItems: 'center',
            borderRadius: 14,
            borderWidth: 1,
            borderColor: 'rgba(255,255,255,0.14)',
            backgroundColor: 'rgba(255,255,255,0.03)',
        },
        pinLogoffButtonText: {
            color: '#cfd7e3',
            fontSize: 15,
            fontWeight: '600',
        },
        savedLoginStatusText: {
            color: '#9aa7ba',
            fontSize: 13,
            lineHeight: 18,
        },
        pinStatusPanel: {
            marginTop: 14,
            paddingHorizontal: 14,
            paddingVertical: 12,
            borderRadius: 16,
            borderWidth: 1,
            borderColor: 'rgba(255,255,255,0.08)',
            backgroundColor: 'rgba(255,255,255,0.025)',
            gap: 8,
        },
        secondaryDeviceActionsPanel: {
            marginTop: 10,
            gap: 2,
        },
        secondaryDeviceActionButton: {
            paddingVertical: 10,
            alignItems: 'center',
            borderRadius: 12,
        },
        secondaryDeviceActionButtonText: {
            color: '#7eb6ff',
            fontSize: 14,
            fontWeight: '600',
        },
        setupButton: {
            borderRadius: 16,
            minHeight: 52,
            marginTop: 12,
            backgroundColor: colors.primary,
        },
        setupLogoffButtonText: {
            color: '#cfd7e3',
            fontSize: 15,
            fontWeight: '600',
        },
        formRow: {
            flexDirection: 'row',
            gap: 14,
        },
        formColumn: {
            flex: 1,
        },
        fullWidthInputContainer: {
            width: '100%',
            paddingHorizontal: 0,
            marginTop: 10,
        },
        fullWidthInputField: {
            ...sharedStyles.inputContainerStyle,
            borderBottomWidth: 0,
        },
        fullWidthInputText: {
            ...sharedStyles.inputStyle,
            textAlign: 'left',
        },
        formSpacer: {
            minHeight: 1,
        },
        wizardSteps: {
            marginTop: 20,
            gap: 12,
        },
        wizardStepRow: {
            flexDirection: 'row',
            alignItems: 'center',
        },
        wizardStepCard: {
            flexDirection: 'row',
            alignItems: 'flex-start',
            gap: 12,
            padding: 14,
            borderRadius: 18,
            borderWidth: 1,
            borderColor: 'rgba(255,255,255,0.04)',
            backgroundColor: 'rgba(255,255,255,0.02)',
        },
        wizardStepCardActive: {
            borderColor: 'rgba(126,182,255,0.45)',
            backgroundColor: 'rgba(126,182,255,0.08)',
        },
        wizardStepCardComplete: {
            borderColor: 'rgba(52,199,89,0.3)',
            backgroundColor: 'rgba(52,199,89,0.08)',
        },
        wizardStepDot: {
            width: 12,
            height: 12,
            borderRadius: 6,
            marginTop: 6,
            backgroundColor: 'rgba(255,255,255,0.16)',
            borderWidth: 1,
            borderColor: 'rgba(255,255,255,0.2)',
        },
        wizardStepDotActive: {
            backgroundColor: colors.primary,
            borderColor: colors.primary,
        },
        wizardStepDotComplete: {
            backgroundColor: '#34c759',
            borderColor: '#34c759',
        },
        wizardStepText: {
            color: '#c7d0dc',
            fontSize: 14,
            lineHeight: 20,
        },
        wizardStepCopy: {
            flex: 1,
            gap: 4,
        },
        wizardStepTitle: {
            color: '#f3f7ff',
            fontSize: 16,
            fontWeight: '700',
        },
        setupSectionCard: {
            borderRadius: 22,
            paddingHorizontal: 18,
            paddingVertical: 18,
            borderWidth: 1,
            borderColor: 'rgba(255,255,255,0.08)',
            backgroundColor: 'rgba(255,255,255,0.03)',
        },
        setupSectionEyebrow: {
            color: '#7eb6ff',
            textTransform: 'uppercase',
            letterSpacing: 1.6,
            fontSize: 11,
            fontWeight: '700',
            marginBottom: 8,
        },
        setupSectionTitle: {
            color: '#f4f8ff',
            fontSize: 21,
            fontWeight: '700',
            marginBottom: 6,
        },
        setupSectionHint: {
            color: '#9ca8b8',
            fontSize: 14,
            lineHeight: 21,
            marginBottom: 8,
        },
        setupActionRow: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 12,
            marginTop: 4,
        },
        setupPrimaryAction: {
            flex: 1,
        },
        setupSecondaryButton: {
            minHeight: 52,
            paddingHorizontal: 12,
            borderRadius: 16,
            borderWidth: 1,
            borderColor: 'rgba(255,255,255,0.12)',
            backgroundColor: 'rgba(255,255,255,0.03)',
        },
        syncStatusCard: {
            justifyContent: 'center',
        },
        syncStatusPanel: {
            marginTop: 16,
            borderRadius: 22,
            paddingHorizontal: 18,
            paddingVertical: 14,
            borderWidth: 1,
            borderColor: 'rgba(255,255,255,0.08)',
            backgroundColor: 'rgba(255,255,255,0.03)',
        },
        syncStatusRow: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            minHeight: 34,
        },
        syncStatusLabel: {
            color: '#c7d0dc',
            fontSize: 14,
            fontWeight: '600',
        },
        syncStatusValue: {
            color: '#eef4ff',
            fontSize: 14,
            fontWeight: '700',
        },
        syncStatusDivider: {
            height: 1,
            backgroundColor: 'rgba(255,255,255,0.08)',
            marginVertical: 4,
        },
        syncHintCard: {
            marginTop: 14,
            borderRadius: 18,
            paddingHorizontal: 16,
            paddingVertical: 14,
            borderWidth: 1,
            borderColor: 'rgba(126,182,255,0.18)',
            backgroundColor: 'rgba(126,182,255,0.08)',
        },
        syncHintTitle: {
            color: '#f4f8ff',
            fontSize: 16,
            fontWeight: '700',
            marginBottom: 6,
        },
        syncHintText: {
            color: '#bdd4f5',
            fontSize: 14,
            lineHeight: 21,
        },
        syncPulseDot: {
            width: 12,
            height: 12,
            borderRadius: 6,
            marginTop: 6,
            backgroundColor: '#7eb6ff',
            borderWidth: 1,
            borderColor: '#7eb6ff',
            opacity: 0.95,
        },
        brandMark: {
            width: 104,
            height: 104,
            opacity: 0.98,
        },
        readyHero: {
            flex: 0.95,
            backgroundColor: '#10141b',
            borderRadius: 30,
            padding: 30,
            borderWidth: 1,
            borderColor: 'rgba(255, 255, 255, 0.08)',
            justifyContent: 'space-between',
        },
        readyBrandMark: {
            width: 88,
            height: 88,
            marginBottom: 16,
            opacity: 0.98,
        },
        readyTitle: {
            color: '#f3f7ff',
            fontSize: 40,
            fontWeight: '700',
            marginBottom: 12,
            maxWidth: 360,
        },
        readySubtitle: {
            color: '#a3adba',
            fontSize: 16,
            lineHeight: 25,
            maxWidth: 380,
        },
        readyMetaRow: {
            flexDirection: 'row',
            gap: 12,
            marginTop: 28,
        },
        readyMetaChip: {
            flex: 1,
            minHeight: 88,
            borderRadius: 20,
            paddingHorizontal: 16,
            paddingVertical: 14,
            borderWidth: 1,
            borderColor: 'rgba(255,255,255,0.08)',
            backgroundColor: 'rgba(255,255,255,0.03)',
            justifyContent: 'space-between',
        },
        readyMetaLabel: {
            color: '#7f8a9a',
            textTransform: 'uppercase',
            letterSpacing: 1.2,
            fontSize: 11,
            fontWeight: '700',
        },
        readyMetaValue: {
            color: '#eef4ff',
            fontSize: 18,
            fontWeight: '700',
        },
        readyRoutesPanel: {
            flex: 1.45,
            backgroundColor: '#0c1016',
            borderRadius: 30,
            paddingHorizontal: 22,
            paddingVertical: 24,
            borderWidth: 1,
            borderColor: 'rgba(255,255,255,0.08)',
        },
        readyRoutesEyebrow: {
            color: '#7f8a9a',
            textTransform: 'uppercase',
            letterSpacing: 1.6,
            fontSize: 11,
            fontWeight: '700',
            marginBottom: 16,
            marginLeft: 6,
        },
        routeGrid: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            justifyContent: 'flex-start',
            alignItems: 'stretch',
            marginHorizontal: -8,
        },
        bigButton: {
            backgroundColor: '#10141b',
            borderRadius: 24,
            margin: 8,
            padding: 22,
            width: 252,
            minHeight: 230,
            borderWidth: 1,
            borderColor: 'rgba(255,255,255,0.08)',
            overflow: 'hidden',
        },
        routeCard: {
            alignItems: 'stretch',
            justifyContent: 'space-between',
        },
        routeAccent: {
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            height: 4,
        },
        routeCardTop: {
            flexDirection: 'row',
            alignItems: 'flex-start',
            justifyContent: 'space-between',
        },
        routeIconWrap: {
            width: 72,
            height: 72,
            borderRadius: 22,
            alignItems: 'center',
            justifyContent: 'center',
        },
        routeIcon: {},
        routeCardBody: {
            marginTop: 18,
        },
        routeEyebrow: {
            color: '#7f8a9a',
            textTransform: 'uppercase',
            letterSpacing: 1.6,
            fontSize: 11,
            fontWeight: '700',
            marginBottom: 10,
        },
        routeTitle: {
            color: '#f3f7ff',
            fontSize: 24,
            fontWeight: '700',
        },
        routeSubtitle: {
            color: '#a3adba',
            fontSize: 14,
            lineHeight: 21,
            marginTop: 10,
        },
    });
};

export type HomeScreenStyles = ReturnType<typeof useHomeScreenStyles>;
