import { StyleSheet } from 'react-native';
import { useDesignTokens } from '@pos/theme/native/design-tokens';

export const useDiscountsStyles = (tokens: ReturnType<typeof useDesignTokens>) =>
  StyleSheet.create({
    page: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 24,
      backgroundColor: '#000000',
    },
    card: {
      width: '100%',
      maxWidth: 680,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: '#1f2937',
      backgroundColor: '#0f131b',
      paddingHorizontal: 28,
      paddingVertical: 32,
    },
    eyebrow: {
      color: '#60a5fa',
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 1.6,
      marginBottom: 12,
    },
    title: {
      color: '#ffffff',
      fontSize: 32,
      fontWeight: '700',
      marginBottom: 12,
    },
    description: {
      color: '#9ca3af',
      fontSize: 16,
      lineHeight: 24,
    },
    screen: { flex: 1 },
    scrollContent: {
      paddingHorizontal: tokens.spacing.xl,
      paddingTop: tokens.spacing.lg,
      paddingBottom: tokens.spacing.xl,
      alignItems: 'center',
    },
    container: { width: '100%', maxWidth: 980 },
    headerCard: {
      marginBottom: tokens.spacing.lg,
      borderRadius: 26,
      borderWidth: 1,
      borderColor: '#C7D0DB22',
      backgroundColor: '#080B10',
      padding: tokens.spacing.lg,
    },
    headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: tokens.spacing.md },
    headerCopy: { flex: 1 },
    headerEyebrow: {
      color: tokens.colors.accent,
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 1.6,
      textTransform: 'uppercase',
      marginBottom: 4,
    },
    headerTitle: {
      color: tokens.colors.textPrimary,
      fontSize: 30,
      fontWeight: '800',
      letterSpacing: -0.6,
    },
    headerSubtitle: {
      color: tokens.colors.textSecondary,
      marginTop: tokens.spacing.xs,
      fontSize: 14,
      lineHeight: 20,
    },
    headerButtonContainer: { alignSelf: 'flex-start' },
    headerButton: { minHeight: 48, borderRadius: 18, paddingHorizontal: 18, backgroundColor: tokens.colors.accent },
    headerButtonTitle: { color: '#ffffff', fontSize: 15, fontWeight: '800' },
    emptyCard: { padding: tokens.spacing.lg, minHeight: 240 },
    listWrap: { gap: tokens.spacing.sm },
    listCard: {
      borderRadius: 22,
      borderWidth: 1,
      borderColor: '#C7D0DB22',
      backgroundColor: '#0E141C',
      paddingVertical: tokens.spacing.md,
      paddingHorizontal: tokens.spacing.md,
    },
    listRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    listTouchArea: { flex: 1 },
    listCopy: { flex: 1, paddingRight: tokens.spacing.md },
    listAside: { alignItems: 'flex-end', gap: tokens.spacing.xs },
    listActionRow: { flexDirection: 'row', gap: tokens.spacing.xs },
    listActionButton: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: `${tokens.colors.accent}44`,
      backgroundColor: `${tokens.colors.accent}14`,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    listDeleteButton: {
      borderColor: '#7f1d1d',
      backgroundColor: '#2b1212',
    },
    listTitle: { color: tokens.colors.textPrimary, fontSize: 18, fontWeight: '700' },
    metaChipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: tokens.spacing.xs, marginTop: tokens.spacing.xs },
    metaChip: {
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderWidth: 1,
      borderColor: `${tokens.colors.accent}44`,
      backgroundColor: `${tokens.colors.accent}18`,
      alignSelf: 'flex-start',
    },
    metaChipText: { color: tokens.colors.accent, fontSize: 11, fontWeight: '800' },
    listMeta: { color: tokens.colors.textSecondary, fontSize: 14, marginTop: 4 },
    editHint: { color: tokens.colors.accent, fontSize: 13, fontWeight: '700' },
    inactivePill: { borderRadius: 999, backgroundColor: '#3f1d1d', paddingHorizontal: 10, paddingVertical: 6 },
    inactivePillText: { color: '#fca5a5', fontSize: 12, fontWeight: '800' },
    sectionCard: {
      marginBottom: tokens.spacing.lg,
      borderRadius: 24,
      borderColor: '#C7D0DB22',
      backgroundColor: '#0E141C',
    },
    sectionTitle: {
      color: tokens.colors.textPrimary,
      fontSize: 19,
      fontWeight: '800',
      letterSpacing: 0.2,
      marginBottom: tokens.spacing.xs,
    },
    sectionSubtitle: {
      color: tokens.colors.textMuted,
      fontSize: 13,
      lineHeight: 18,
      marginBottom: tokens.spacing.md,
    },
    previewCard: {
      marginTop: tokens.spacing.md,
      borderRadius: tokens.radii.md,
      borderWidth: 1,
      borderColor: tokens.colors.border,
      backgroundColor: tokens.colors.surfaceMuted,
      padding: tokens.spacing.sm,
    },
    previewTitle: { color: tokens.colors.textPrimary, fontSize: 14, fontWeight: '800', marginBottom: 4 },
    previewBody: { color: tokens.colors.textSecondary, fontSize: 13, lineHeight: 18 },
    fieldLabel: { color: tokens.colors.textSecondary, fontSize: 13, fontWeight: '700', marginTop: tokens.spacing.xs },
    fieldHint: {
      color: tokens.colors.textSecondary,
      fontSize: 12,
      lineHeight: 17,
      marginTop: tokens.spacing.xs,
      marginHorizontal: 10,
    },
    formGrid: { flexDirection: 'row', gap: tokens.spacing.md },
    formColumn: { flex: 1 },
    formColumnWide: { width: '100%' },
    advancedToggle: {
      marginVertical: tokens.spacing.sm,
      borderRadius: tokens.radii.sm,
      borderWidth: 1,
      borderColor: `${tokens.colors.accent}44`,
      backgroundColor: `${tokens.colors.accent}12`,
      paddingVertical: tokens.spacing.sm,
      paddingHorizontal: tokens.spacing.sm,
      alignItems: 'center',
    },
    advancedToggleText: { color: tokens.colors.accent, fontSize: 13, fontWeight: '800' },
    toggleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: tokens.spacing.sm,
      borderBottomWidth: 1,
      borderBottomColor: tokens.colors.border,
    },
    toggleRowNoBorder: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: tokens.spacing.sm,
    },
    toggleLabel: { color: tokens.colors.textPrimary, fontSize: 15, fontWeight: '600', flex: 1, paddingRight: tokens.spacing.md },
    actionBar: {
      paddingHorizontal: tokens.spacing.xl,
      paddingBottom: tokens.spacing.md,
      paddingTop: tokens.spacing.xs,
    },
    actionBarCard: {
      maxWidth: 980,
      alignSelf: 'center',
      width: '100%',
      borderRadius: 24,
      borderColor: '#C7D0DB22',
      backgroundColor: '#080B10',
    },
    formActionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: tokens.spacing.md,
    },
    deleteButton: {
      borderRadius: tokens.radii.md,
      borderWidth: 1,
      borderColor: '#7f1d1d',
      backgroundColor: '#2b1212',
      paddingVertical: tokens.spacing.sm,
      paddingHorizontal: tokens.spacing.md,
      alignItems: 'center',
    },
    deleteButtonText: {
      color: '#fca5a5',
      fontSize: 15,
      fontWeight: '700',
    },
    inlineDeleteButton: {
      marginBottom: 0,
    },
    listDeleteText: {
      color: '#fca5a5',
      fontSize: 13,
      fontWeight: '700',
    },
  });

export type DiscountsStyles = ReturnType<typeof useDiscountsStyles>;
